/**
 * Telegram Types
 *
 * Core data types for Telegram integration.
 */

/**
 * A message received from Telegram
 */
export interface TelegramMessage {
  /** Unique message ID (UUID generated by Mudpuppy) */
  id: string;
  /** Telegram user ID who sent the message */
  userId: number;
  /** Username (if available) */
  username?: string;
  /** First name */
  firstName?: string;
  /** Message text content */
  text: string;
  /** Unix timestamp when message was received */
  timestamp: number;
  /** Whether this message has been read/processed */
  read: boolean;
  /** Original Telegram message ID */
  telegramMessageId: number;
  /** Chat ID (same as userId for DMs) */
  chatId: number;
}

/**
 * A pending pairing request from a Telegram user
 */
export interface PairingRequest {
  /** Unique request ID (UUID) */
  id: string;
  /** Telegram user ID requesting pairing */
  userId: number;
  /** Username (if available) */
  username?: string;
  /** First name */
  firstName?: string;
  /** Unix timestamp when request was created */
  createdAt: number;
  /** Request status */
  status: 'pending' | 'approved' | 'denied';
}

/**
 * A paired Telegram user
 */
export interface PairedUser {
  /** Telegram user ID */
  id: number;
  /** Username (if available) */
  username?: string;
  /** First name */
  firstName?: string;
  /** Unix timestamp when user was paired */
  pairedAt: number;
  /** Total messages received from this user */
  messageCount: number;
}

/**
 * Status of the Telegram bot daemon
 */
export interface BotStatus {
  /** Whether the daemon process is running */
  running: boolean;
  /** Bot username (if connected) */
  botUsername?: string;
  /** Bot display name */
  botName?: string;
  /** Unix timestamp when daemon started */
  startedAt?: number;
  /** Daemon process ID */
  pid?: number;
  /** Number of paired users */
  pairedUsers: number;
  /** Number of pending pairing requests */
  pendingRequests: number;
  /** Number of unread messages */
  unreadMessages: number;
  /** Last error message (if any) */
  lastError?: string;
}

/**
 * Result of sending a message
 */
export interface SendResult {
  /** Whether send was successful */
  success: boolean;
  /** Telegram message ID of sent message */
  messageId?: number;
  /** Error message if failed */
  error?: string;
}

/**
 * Options for polling messages
 */
export interface PollOptions {
  /** Only return unread messages (default: true) */
  unreadOnly?: boolean;
  /** Maximum number of messages to return */
  limit?: number;
  /** Filter by user ID */
  userId?: number;
  /** Mark returned messages as read (default: true) */
  markAsRead?: boolean;
}

/**
 * Options for sending a message
 */
export interface SendOptions {
  /** User ID to send to */
  userId: number;
  /** Message text */
  text: string;
  /** Parse mode for Telegram (default: HTML) */
  parseMode?: 'HTML' | 'Markdown' | 'MarkdownV2';
  /** Whether to disable link previews */
  disableLinkPreview?: boolean;
  /** Message to reply to (optional) */
  replyToMessageId?: number;
}

/**
 * Options for managing pairings
 */
export interface PairOptions {
  /** Action to perform */
  action: 'list' | 'approve' | 'deny' | 'revoke';
  /** User ID (required for approve/deny/revoke) */
  userId?: number;
  /** Request ID (alternative to userId for approve/deny) */
  requestId?: string;
}
